### PR TITLE
Notes on townhall meeting #1 2021-09-18

### PR DESCRIPTION
**Pull request by kempsterrrr**

### CODE REVIEW

**Comment by kempsterrrr** [comment]
Sorry for inconsistent formatting on this compared to other meeting notes, was rushing to get it done alongside cooking.

Happy to amend tomorrow morning if we like but away from computer now.

**Comment by kempsterrrr** [comment]
Can't sleep so took another pass at these notes to match the format used for first meeting. Hope this is much easier for people to follow. Any changes or things missed please feel free to add but LGTM asap so community has easy to access reference :)

**Comment by with-heart** [comment]
I don't have time to integrate them with yours rn (if they're even worth integrating) but here are my notes from yesterday:

- Introductions
- Nader isn't necessarily going to be around so it's on us to do things and make decisions and figure out what we're doing
- Need to decide on a schedule for meetings
    - The time we chose (-5GMT) is perfect time
    - Will post an emoji-vote poll
- Project meetings can be autonomous, with updates given to broader community
    - Projects should have their schedules in the open as well
- Onboarding documentation
    - New users don't realize they could 
- Community automation
    - Discord bots
        - Need people to access to have be able to add bots
        - Event bot
        - "Choose your own roles" bot
            - Areas of focus, etc.
            - Assigns roles that provide access to various channels based on what you're interested in
        - Onboarding bot
    - Twitter account
        - Could post about events and such
- Token
    - Airdrop of dev bucks
        - ERC20 token
    - Rewarding dev bucks for completing work/doing stuff
    - Making token more valuable so that we can attract more talent to work on the DAO/community projects
    - Need a way to sponsor/contribute
        - Example was wanting to give 1 ETH, how would we make that happen?
- What we need to focus on defining/figuring out
    - Token
    - Governance
- Discourse
    - Very important—allows us to create a historical record of discussion, decisions, context, etc.
    - @kempsterrrr and @dhaiwat to handle getting that set up
- Documenting the DAO
    - Blog
    - Learning in public as a collective allows us to answer our own questions/solve our own problems and teach others how to also do the same thing we're doing

If anyone wants to make a PR adding anything worth adding from my notes, I'd love you forever 😁

**Comment by kempsterrrr** [comment]
I will take a look at adding these in later @with-heart thanks for sharing !

**Pull request merged**
